feign:
  hystrix:
    enabled: false
webhooks:
  discord:
    host: "https://discordapp.com"
    uri: "/api/webhooks/704810377099345930/QZbel_JmuCOFVu0HiHJTloaHxb1nqM7v4USGk4Vy_0NXW7crrGwElF410vekqjk2zUWl"

tile:
  player-joined:
    author: "Conceierge Bot"
    title: "Player left the server!"
    thumbnailUrl: "https://mc-log-bot-assets.s3.us-east-2.amazonaws.com/pickaxe.png"
    color: 65280