feign:
  hystrix:
    enabled: false
apps:
  discord:
    hookHost: "https://discordapp.com"
    hookUri: "/api/webhooks/HOOK/PATH"
tailer:
  enabled: true
  logFile: "server.log"
  readDelayMillis: 1000
  readFromEnd: true
  closeFileBetweenChunks: true
bot:
  player-joined:
    enabled: true
    author: "Attendance Bot"
    title: "Player joined the server!"
    thumbnailUrl: "https://mc-log-bot-assets.s3.us-east-2.amazonaws.com/pickaxe.png"
    color: 65280
  achievement:
    enabled: true
    author: "Achievement Bot"
    title: "Somebody earned an achievment!"
    thumbnailUrl: "https://mc-log-bot-assets.s3.us-east-2.amazonaws.com/trophy.png"
    color: 16766720
  death:
    enabled: true
    author: "Death Bot"
    thumbnailUrl: "https://mc-log-bot-assets.s3.us-east-2.amazonaws.com/reaper.png"
    color: 9109504